train_config:
  results_dir: experiments/bbob/search
  problem_type: bbob
  strategy_name: "Sep_CMA_ES"
  popsize: 32
  num_dims: 20
  num_eval_runs: 50  # How often to run experiment in batch mode
  num_generations: 100
  es_params:
    init_min: -5.0
    init_max: 5.0
  es_config:
    sigma_init: 0.5
  num_hyper_search_iters: 50
  search_config:
    refine_after: 40
    refine_top_k: 10

log_config:
  time_to_track: 
    - "search_iter"
    - "num_gens"
  what_to_track:
    - "test_eval_perf"
    - "Sphere_mean"
    - "Sphere_best"
    - "EllipsoidalOriginal_mean"
    - "EllipsoidalOriginal_best"
    - "RastriginOriginal_mean"
    - "RastriginOriginal_best"
    - "BuecheRastrigin_mean"
    - "BuecheRastrigin_best"
    - "LinearSlope_mean"
    - "LinearSlope_best"
    - "AttractiveSector_mean"
    - "AttractiveSector_best"
    - "StepEllipsoidal_mean"
    - "StepEllipsoidal_best"
    - "RosenbrockOriginal_mean"
    - "RosenbrockOriginal_best"
    - "RosenbrockRotated_mean"
    - "RosenbrockRotated_best"
    - "EllipsoidalRotated_mean"
    - "EllipsoidalRotated_best"
    - "Discus_mean"
    - "Discus_best"
    - "BentCigar_mean"
    - "BentCigar_best"
    - "SharpRidge_mean"
    - "SharpRidge_best"
    - "DifferentPowers_mean"
    - "DifferentPowers_best"
    - "RastriginRotated_mean"
    - "RastriginRotated_best"
    - "Weierstrass_mean"
    - "Weierstrass_best"
    - "SchaffersF7_mean"
    - "SchaffersF7_best"
    - "SchaffersF7IllConditioned_mean"
    - "SchaffersF7IllConditioned_best"
    - "GriewankRosenbrock_mean"
    - "GriewankRosenbrock_best"
    - "Schwefel_mean"
    - "Schwefel_best"
    - "Lunacek_mean"
    - "Lunacek_best"
    - "Gallagher101Me_mean"
    - "Gallagher101Me_best"
    - "Gallagher21Hi_mean"
    - "Gallagher21Hi_best"
  what_to_print:
    - "test_eval_perf"
    # - "Sphere_best"
    # - "AttractiveSector_best"
    # - "EllipsoidalRotated_best"
    # - "RastriginRotated_best"
    # - "Schwefel_best"
  verbose: true
  print_every_k_updates: 1
  overwrite: 1
  model_type: "jax"
  use_wandb: false
  wandb_config:
    project: es-bench
    group: bbob
    name: seed0

device_config:
  device_type: "gpu"
  num_devices: 1