train_config:
  results_dir: experiments/fmnist_classify/search
  num_generations: 4000
  eval_every_gen: 100
  strategy_name: SNES
  popsize: 128
  problem_type: mnist_classify
  env_name: fmnist
  model_config:
    num_hidden_layers: 0
    num_hidden_units: 0
  task_config:
    batch_size: 1024
  es_config:
    sigma_init: 0.001
  es_params:
    init_min: 0.0
    init_max: 0.0
  num_hyper_search_iters: 50
  search_config:
    refine_after: 40
    refine_top_k: 10

log_config:
  time_to_track:
    - "search_iter" 
    - "num_gens"
  what_to_track: 
    - "mean_pop_perf"
    - "max_pop_perf"
    - "min_pop_perf"
    - "best_pop_perf"
    - "test_eval_perf"
    - "best_eval_perf"
  verbose: true
  print_every_k_updates: 1
  overwrite: 1
  model_type: "jax"
  use_wandb: true
  wandb_config:
    project: neb
    group: fmnist_classify
    name: seed0

device_config:
  device_type: "gpu"
  num_devices: 1